import 'dart:convert';

/// Custom ESC/POS command generator for thermal printers
/// Works with 58mm and 80mm printers
class EscPosGenerator {
  final int paperWidth; // in characters (32 for 58mm, 48 for 80mm)
  List<int> _buffer = [];

  EscPosGenerator({this.paperWidth = 32});

  /// Factory for 58mm paper
  factory EscPosGenerator.mm58() => EscPosGenerator(paperWidth: 32);

  /// Factory for 80mm paper
  factory EscPosGenerator.mm80() => EscPosGenerator(paperWidth: 48);

  /// Get the generated bytes
  List<int> get bytes => List<int>.from(_buffer);

  /// Clear the buffer
  void clear() {
    _buffer = [];
  }

  /// ESC/POS Commands
  static const List<int> _cmdInit = [0x1B, 0x40]; // ESC @
  static const List<int> _cmdLF = [0x0A]; // Line Feed
  static const List<int> _cmdAlignLeft = [0x1B, 0x61, 0x00]; // ESC a 0
  static const List<int> _cmdAlignCenter = [0x1B, 0x61, 0x01]; // ESC a 1
  static const List<int> _cmdAlignRight = [0x1B, 0x61, 0x02]; // ESC a 2
  static const List<int> _cmdBoldOn = [0x1B, 0x45, 0x01]; // ESC E 1
  static const List<int> _cmdBoldOff = [0x1B, 0x45, 0x00]; // ESC E 0
  static const List<int> _cmdDoubleHeight = [0x1B, 0x21, 0x10]; // ESC ! 16
  static const List<int> _cmdDoubleWidth = [0x1B, 0x21, 0x20]; // ESC ! 32
  static const List<int> _cmdDoubleSize = [0x1B, 0x21, 0x30]; // ESC ! 48 (double height + width)
  static const List<int> _cmdNormalSize = [0x1B, 0x21, 0x00]; // ESC ! 0
  static const List<int> _cmdCut = [0x1D, 0x56, 0x00]; // GS V 0 (full cut)
  static const List<int> _cmdPartialCut = [0x1D, 0x56, 0x01]; // GS V 1 (partial cut)

  /// Initialize printer
  void init() {
    _buffer.addAll(_cmdInit);
  }

  /// Add text with optional styles
  void text(
    String content, {
    bool bold = false,
    bool doubleHeight = false,
    bool doubleWidth = false,
    TextAlign align = TextAlign.left,
  }) {
    // Set alignment
    switch (align) {
      case TextAlign.center:
        _buffer.addAll(_cmdAlignCenter);
        break;
      case TextAlign.right:
        _buffer.addAll(_cmdAlignRight);
        break;
      default:
        _buffer.addAll(_cmdAlignLeft);
    }

    // Set size
    if (doubleHeight && doubleWidth) {
      _buffer.addAll(_cmdDoubleSize);
    } else if (doubleHeight) {
      _buffer.addAll(_cmdDoubleHeight);
    } else if (doubleWidth) {
      _buffer.addAll(_cmdDoubleWidth);
    } else {
      _buffer.addAll(_cmdNormalSize);
    }

    // Set bold
    if (bold) {
      _buffer.addAll(_cmdBoldOn);
    }

    // Add text (convert to bytes using Latin-1 for thermal printer compatibility)
    _buffer.addAll(_encodeText(content));

    // Reset bold
    if (bold) {
      _buffer.addAll(_cmdBoldOff);
    }

    // Reset size
    _buffer.addAll(_cmdNormalSize);

    // Line feed
    _buffer.addAll(_cmdLF);

    // Reset alignment to left
    _buffer.addAll(_cmdAlignLeft);
  }

  /// Add a horizontal rule/divider
  void hr({String char = '-'}) {
    _buffer.addAll(_encodeText(char * paperWidth));
    _buffer.addAll(_cmdLF);
  }

  /// Add empty lines
  void feed(int lines) {
    for (int i = 0; i < lines; i++) {
      _buffer.addAll(_cmdLF);
    }
  }

  /// Add a row with left and right text (for item + price)
  void row(String left, String right) {
    int maxLeftWidth = paperWidth - right.length - 1;
    String leftTrimmed =
        left.length > maxLeftWidth ? left.substring(0, maxLeftWidth) : left.padRight(maxLeftWidth);
    String line = '$leftTrimmed $right';
    _buffer.addAll(_encodeText(line));
    _buffer.addAll(_cmdLF);
  }

  /// Add a row with left bold and right text
  void rowBold(String left, String right) {
    _buffer.addAll(_cmdBoldOn);
    row(left, right);
    _buffer.addAll(_cmdBoldOff);
  }

  /// Add a row with 4 columns
  /// Widths are percentages/ratios of total paper width
  /// Default: col1 (4/10), col2 (1/10), col3 (2/10), col4 (3/10)
  void row4(String col1, String col2, String col3, String col4) {
    int w1 = (paperWidth * 0.45).floor(); // Item
    int w2 = (paperWidth * 0.10).floor(); // Qty
    int w3 = (paperWidth * 0.20).floor(); // Disc
    int w4 = paperWidth - w1 - w2 - w3; // Total (remainder)

    // Truncate or pad
    String c1 = col1.length > w1 ? col1.substring(0, w1) : col1.padRight(w1);
    String c2 = col2.length > w2 ? col2.substring(0, w2) : col2.padLeft(w2);
    String c3 = col3.length > w3 ? col3.substring(0, w3) : col3.padLeft(w3);
    String c4 = col4.length > w4 ? col4.substring(0, w4) : col4.padLeft(w4);

    _buffer.addAll(_encodeText('$c1$c2$c3$c4'));
    _buffer.addAll(_cmdLF);
  }

  /// Cut paper (if printer supports it)
  void cut({bool partial = false}) {
    feed(3); // Feed before cut
    _buffer.addAll(partial ? _cmdPartialCut : _cmdCut);
  }

  /// Encode text to bytes (using code page PC437/Latin-1)
  List<int> _encodeText(String text) {
    // Replace Indonesian characters that might not be in basic ASCII
    String safeText = text
        .replaceAll('Rp', 'Rp') // Keep Rp as is
        .replaceAll('–', '-')
        .replaceAll('—', '-')
        .replaceAll(''', "'")
        .replaceAll(''', "'")
        .replaceAll('"', '"')
        .replaceAll('"', '"');

    try {
      return latin1.encode(safeText);
    } catch (e) {
      // Fallback to ASCII if Latin-1 fails
      return safeText.codeUnits.map((c) => c > 127 ? 63 : c).toList(); // Replace non-ASCII with '?'
    }
  }

  /// Print QR Code
  /// [content] Text to encode
  /// [size] Module size (1-16)
  void qrcode(String content, {int size = 5, TextAlign align = TextAlign.center}) {
    // Alignment
    switch (align) {
      case TextAlign.center:
        _buffer.addAll(_cmdAlignCenter);
        break;
      case TextAlign.right:
        _buffer.addAll(_cmdAlignRight);
        break;
      default:
        _buffer.addAll(_cmdAlignLeft);
        break;
    }

    // QR Code commands

    // 1. Model: Model 2
    // GS ( k 04 00 31 41 n1 n2 -> 1D 28 6B 04 00 31 41 32 00
    _buffer.addAll([0x1d, 0x28, 0x6b, 0x04, 0x00, 0x31, 0x41, 0x32, 0x00]);

    // 2. Module size
    // GS ( k 03 00 31 43 n -> 1D 28 6B 03 00 31 43 n
    _buffer.addAll([0x1d, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x43, size]);

    // 3. Error correction: Level L
    // GS ( k 03 00 31 45 n -> 1D 28 6B 03 00 31 45 30 (48 = '0' = L)
    _buffer.addAll([0x1d, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x45, 48]);

    // 4. Store data
    // GS ( k pL pH 31 50 30 d1...dk
    List<int> data = latin1.encode(content);
    int len = data.length + 3; // +3 for 31 50 30
    int pL = len % 256;
    int pH = len ~/ 256;
    _buffer.addAll([0x1d, 0x28, 0x6b, pL, pH, 0x31, 0x50, 0x30]);
    _buffer.addAll(data);

    // 5. Print
    // GS ( k 03 00 31 51 30 -> 1D 28 6B 03 00 31 51 30
    _buffer.addAll([0x1d, 0x28, 0x6b, 0x03, 0x00, 0x31, 0x51, 0x30]);

    // Reset alignment
    _buffer.addAll(_cmdAlignLeft);
  }
}

enum TextAlign { left, center, right }
