import 'dart:convert';

/// Custom ESC/POS command generator for thermal printers
/// Works with 58mm and 80mm printers
class EscPosGenerator {
  final int paperWidth; // in characters (32 for 58mm, 48 for 80mm)
  List<int> _buffer = [];

  EscPosGenerator({this.paperWidth = 32});

  /// Factory for 58mm paper
  factory EscPosGenerator.mm58() => EscPosGenerator(paperWidth: 32);

  /// Factory for 80mm paper
  factory EscPosGenerator.mm80() => EscPosGenerator(paperWidth: 48);

  /// Get the generated bytes
  List<int> get bytes => List<int>.from(_buffer);

  /// Clear the buffer
  void clear() {
    _buffer = [];
  }

  /// ESC/POS Commands
  static const List<int> _cmdInit = [0x1B, 0x40]; // ESC @
  static const List<int> _cmdLF = [0x0A]; // Line Feed
  static const List<int> _cmdAlignLeft = [0x1B, 0x61, 0x00]; // ESC a 0
  static const List<int> _cmdAlignCenter = [0x1B, 0x61, 0x01]; // ESC a 1
  static const List<int> _cmdAlignRight = [0x1B, 0x61, 0x02]; // ESC a 2
  static const List<int> _cmdBoldOn = [0x1B, 0x45, 0x01]; // ESC E 1
  static const List<int> _cmdBoldOff = [0x1B, 0x45, 0x00]; // ESC E 0
  static const List<int> _cmdDoubleHeight = [0x1B, 0x21, 0x10]; // ESC ! 16
  static const List<int> _cmdDoubleWidth = [0x1B, 0x21, 0x20]; // ESC ! 32
  static const List<int> _cmdDoubleSize = [0x1B, 0x21, 0x30]; // ESC ! 48 (double height + width)
  static const List<int> _cmdNormalSize = [0x1B, 0x21, 0x00]; // ESC ! 0
  static const List<int> _cmdCut = [0x1D, 0x56, 0x00]; // GS V 0 (full cut)
  static const List<int> _cmdPartialCut = [0x1D, 0x56, 0x01]; // GS V 1 (partial cut)

  /// Initialize printer
  void init() {
    _buffer.addAll(_cmdInit);
  }

  /// Add text with optional styles
  void text(
    String content, {
    bool bold = false,
    bool doubleHeight = false,
    bool doubleWidth = false,
    TextAlign align = TextAlign.left,
  }) {
    // Set alignment
    switch (align) {
      case TextAlign.center:
        _buffer.addAll(_cmdAlignCenter);
        break;
      case TextAlign.right:
        _buffer.addAll(_cmdAlignRight);
        break;
      default:
        _buffer.addAll(_cmdAlignLeft);
    }

    // Set size
    if (doubleHeight && doubleWidth) {
      _buffer.addAll(_cmdDoubleSize);
    } else if (doubleHeight) {
      _buffer.addAll(_cmdDoubleHeight);
    } else if (doubleWidth) {
      _buffer.addAll(_cmdDoubleWidth);
    } else {
      _buffer.addAll(_cmdNormalSize);
    }

    // Set bold
    if (bold) {
      _buffer.addAll(_cmdBoldOn);
    }

    // Add text (convert to bytes using Latin-1 for thermal printer compatibility)
    _buffer.addAll(_encodeText(content));

    // Reset bold
    if (bold) {
      _buffer.addAll(_cmdBoldOff);
    }

    // Reset size
    _buffer.addAll(_cmdNormalSize);

    // Line feed
    _buffer.addAll(_cmdLF);

    // Reset alignment to left
    _buffer.addAll(_cmdAlignLeft);
  }

  /// Add a horizontal rule/divider
  void hr({String char = '-'}) {
    _buffer.addAll(_encodeText(char * paperWidth));
    _buffer.addAll(_cmdLF);
  }

  /// Add empty lines
  void feed(int lines) {
    for (int i = 0; i < lines; i++) {
      _buffer.addAll(_cmdLF);
    }
  }

  /// Add a row with left and right text (for item + price)
  void row(String left, String right) {
    int maxLeftWidth = paperWidth - right.length - 1;
    String leftTrimmed =
        left.length > maxLeftWidth ? left.substring(0, maxLeftWidth) : left.padRight(maxLeftWidth);
    String line = '$leftTrimmed $right';
    _buffer.addAll(_encodeText(line));
    _buffer.addAll(_cmdLF);
  }

  /// Add a row with left bold and right text
  void rowBold(String left, String right) {
    _buffer.addAll(_cmdBoldOn);
    row(left, right);
    _buffer.addAll(_cmdBoldOff);
  }

  /// Cut paper (if printer supports it)
  void cut({bool partial = false}) {
    feed(3); // Feed before cut
    _buffer.addAll(partial ? _cmdPartialCut : _cmdCut);
  }

  /// Encode text to bytes (using code page PC437/Latin-1)
  List<int> _encodeText(String text) {
    // Replace Indonesian characters that might not be in basic ASCII
    String safeText = text
        .replaceAll('Rp', 'Rp') // Keep Rp as is
        .replaceAll('–', '-')
        .replaceAll('—', '-')
        .replaceAll(''', "'")
        .replaceAll(''', "'")
        .replaceAll('"', '"')
        .replaceAll('"', '"');

    try {
      return latin1.encode(safeText);
    } catch (e) {
      // Fallback to ASCII if Latin-1 fails
      return safeText.codeUnits.map((c) => c > 127 ? 63 : c).toList(); // Replace non-ASCII with '?'
    }
  }
}

enum TextAlign { left, center, right }
